spring.application.name=cloud-campus-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cloudcampus
spring.datasource.username=cloudcampus
spring.datasource.password=cloudcampus_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info

server.port=8081
